<? $account = $this->auth()->getManager(); ?>

<div class="banner container navbar">

 <div class="col-md-4">
 <div class="navbar-header">
    <a href="<?=$this->url('home')?>"><img src="http://uns.edu.ar/img/uns_top_left.png"></a>
 </div>
 </div>
        <style>
        .ya {
        font-size:<? if(!$account->isLoggedIn()): ?>2em;<? else: ?>1.8em;<? endif ?>
	color:#ffffff;
	font-family:"Times New Roman',Times,serif";
        }
        @media (max-width: 370px){
                .ya {
                font-size:1.6em;
                }
        }
	#header-collapse{
		background:#ff5733;
	}
	.footer-container{
		background:#ff5733;
	}
        </style>

 <div class="col-md-4 col-md-offset-1 ya">

<!--<h1 class="ya" style="color:#2d62a4; media=" "font-size:8:vw; font-family:'Times New Roman',Times,serif">BIBLIOTECAS</h1></div>-->
	<div class="ya">BIBLIOTECAS</div>
 </div>
 <? if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul role="navigation" class="nav navbar-nav navbar-right flip">

	 <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
<div class="row" style="padding:0px">
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>" >
              <p style="color:#06C;">
                <?= ($account->isLoggedIn())?$account->isLoggedIn()->lastname.", ".$account->isLoggedIn()->firstname:'' ?>
              </p>
            </li>
</div>
          <? endif; ?>
<div class="row" style="padding:0px">

 <div class="col" style="float:left;margin:0.5em;">
          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown" style="text-align:left">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?> style="text-align:left"><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
</div>

          <? if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <? endif; ?>
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <? endif; ?>

          <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
              <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
 <div class="col" style="float:right;margin:0.5em;">
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
 </div>
              <? endif; ?>
            </li>

 <div class="col" style="float:right;margin:0.5em;">
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">

              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
 </div>
 <div class="col" style="float:right;margin:0.5em;">
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i>
                <!--?= ($account->isLoggedIn())?$account->isLoggedIn()->lastname.", ".$account->isLoggedIn()->firstname:'' ?--> <?=$this->transEsc("Your Account")?>
              </a>
            </li>
 </div>
          <? endif; ?>
</div>
        </ul>
      </nav>
   </div>
  <? endif; ?>
</div>
<? if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <nav class="nav searchbox hidden-print">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>
<? endif; ?>
