<? $this->headTitle($this->translate('Información bibliotecas')); ?>

<h1>Información sobre las Bibliotecas</h1>

<h3>Biblioteca Central "Profesor Nicolás Matijevic"</h3>

<p>Dirección: Av. Alem 1253</p>

<p>Horario: 7:30 hs a 19:50 hs</p>

<p>Email: <a href="mailto:bc@uns.edu.ar">bc@uns.edu.ar</a></p>

<p>Sitio Web: <a href="http://bc.uns.edu.ar" target=_blank>bc.uns.edu.ar</a></p>


<h3>Biblioteca de Administración "Contador Renato Terzoli"</h3>

<p>Dirección: 12 de Octubre y San Juan </p>

<p>Horario: 7.30 a 19.00 hs</p>

<p>Email: <a href="mailto:bibadm@uns.edu.ar">bibadm@uns.edu.ar</a></p>

<p>Sitio web: <a href="http://bibadm.uns.edu.ar" target=_blank>bibadm.uns.edu.ar</a></p>


<h3>Biblioteca de Ciencias Agrarias</h3>

<p>Dirección: San Andrés 800 - Altos de Palihue</p>

<p>Horario: 8.00 a 17.30 hs</p>

<p>Email: <a href="mailto:bibagro@uns.edu.ar">bibagro@uns.edu.ar</a></p>

<p>Sitio web: <a href="https://www.uns.edu.ar/deptos/agronomia" target=_blank>www.uns.edu.ar/deptos/agronomia</a></p>


<h3>Biblioteca de Computación</h3>

<p>Dirección: Av. Alem 1253 </p>

<p>Horario: 8.00 a 16.00 hs</p>

<p>Email: <a href="mailto:biblioteca@cs.uns.edu.ar">biblioteca@cs.uns.edu.ar</a></p>

<p>Sitio web: <a href="https://cs.uns.edu.ar/home/" target=_blank>www.cs.uns.edu.ar</a></p>


<h3>Biblioteca de Derecho</h3>

<p>Dirección: Av. Colón 48</p>

<p>Horario: 9.30 a 18.00 hs</p>

<p>Email: <a href="mailto:bibderecho@uns.edu.ar">bibderecho@uns.edu.ar</a></p>

<p>Sitio web: <a href="https://www.derechouns.com.ar/dependencias-y-horarios/" target=_blank>www.derechouns.com.ar</a></p>


<h3>Biblioteca de Economía "Uros Basic"</h3>

<p>Dirección: 12 de Octubre y San Juan</p>

<p>Horario: 7.30 a 19.00 hs</p>

<p>Email: <a href="mailto:bibleco@uns.edu.ar">bibleco@uns.edu.ar</a></p>

<p>Sitio web: <a href="http://bibliotecaeconomiauns.blogspot.com.ar" target=_blank>bibliotecaeconomiauns.blogspot.com.ar</a></p>


<h3>Biblioteca de Geografía y Turismo</h3>

<p>Dirección: 12 de Octubre y San Juan</p>

<p>Horario: 7.30 a 19.45 hs</p>

<p>Email: <a href="mailto:bibliotecadgyt@uns.edu.ar">bibliotecadgyt@uns.edu.ar</a></p>

<p>Sitio web: <a href="http://www.geografiayturismo.uns.edu.ar/biblioteca.php?id=5">www.geografiayturismo.uns.edu.ar/biblioteca.php</a></p>


<h3>Biblioteca de Humanidades "Arturo Marasso"</h3>

<p>Dirección: 12 de Octubre 1098, Planta baja</p>

<p>Horario: 8:00 hs a 20:45 hs</p>

<p>Email: <a href="mailto:bmarasso@uns.edu.ar">bmarasso@uns.edu.ar</a></p>

<p>Sitio web: <a href="http://www.bam.uns.edu.ar" target=_blank>bam.uns.edu.ar</a></p>


<h3>Biblioteca de Matemática</h3>

<p>Dirección: Av. Alem 1253</p>

<p>Horario: 8.00 a 18.00 hs</p>

<p>Email: <a href="mailto:bibima@criba.edu.ar">bibima@criba.edu.ar</a></p>

<p>Sitio web: <a href="http://inmabb-conicet.gob.ar/" target=_blank>inmabb.criba.edu.ar</a></p>


<h3>Biblioteca de PLAPIQUI</h3>

<p>Dirección: Camino La Carrindanga Km. 7</p>

<p>Horario: 9.00 a 17.00 hs</p>

<p>Email: <a href="mailto:biblioteca@plapiqui.edu.ar">biblioteca@plapiqui.edu.ar</a></p>

<p>Sitio web: <a href="http://www.plapiqui.edu.ar/biblioteca/" target=_blank>www.plapiqui.edu.ar/biblioteca<a/></p>


