<p>Presentamos el <strong>catálogo (de próxima generación) de acceso abierto en línea</strong>, el cual permite
<ul>
        <li>autenticación de usuarios</li>  
        <li>visualización del estado de cuenta y autogestión de renovación de libros</li>
        <li>consulta de registros de información (bibliografía en formato impreso, revistas en formato digital editadas en la UNS, tesis digitales 
de posgrado, libros digitales contratados, repositorio institucional y temáticos) de las bibliotecas de la UNS</li>

</ul>
 
<p>Estos servicios estarán disponibles en un primer momento para usuarios que hayan realizado transacciones en la Biblioteca Central.</p>

<p>Posteriormente, se incorporarán las otras bibliotecas de UNS y CONICET que utilicen CaMPI.</p>
 
<p>La autenticación de usuarios funcionará sin restricciones para alumnos<a href="/vufind/Content/asklibrary" target=_top>.</a></p>

<p>Ante consultas acerca del funcionamiento, <a href="#" data-dismiss="modal" onClick="javascript:window.location='/vufind/Content/asklibrary'">contáctenos</a>.</p>

<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>


