<? $this->headTitle($this->translate('FAQs')); ?>

<h1><?=$this->transEsc('FAQs') ?></h1>

<? if ($this->auth()->getManager()->supportsRecovery()): ?>
  <p>
  </p>
<? endif; ?>
<p>
<ul>
	<li>
		<b>¿Qué puedo hacer cuando soy un usuario registrado (logueado)?</b><br>		
Si usted  es un usuario registrado y se encuentra logueado en este catálogo, podrá disponer de nuevas funcionalidades entre las cuales se encuentran:					
		   <ul>
        	<li>Estado de cuenta del usuario en la Biblioteca Central (libros que tiene en su poder, libros reservados y libros que están en espera de ser retirados por usted)</li>
        	<li>Renovación autogestionada: Podrá renovar sus libros a través de este catálogo  (siempre y cuando el material que quiere renovar no posee reservas)</li>
        	<li>Confección una lista de favoritos donde se podrán incorporar diferentes recursos organizados con la posibilidad de estructurarlos en carpetas.</li>
        	<li>Guardar búsquedas realizadas</li>
        	<li>Realizar comentarios a los diferentes materiales</li>
        </ul>
	</li>
</ul>
</p>

<p>
	<ul>
		<li>
			<b>¿Puedo ser un usuario registrado (logueado) de este catálogo?</b><br>
Para poder ser usuario registrado (logueado) de este catálogo deberá pertenecer a la comunidad universitaria de la Universidad Nacional del Sur (UNS), ser personal de la UNS y/o ser un usuario registrado de las Bibliotecas de la UNS.
		</li>
	</ul>
</p>

<p>
	<ul>
		<li>
			<b>¿Cómo hago para ser un usuario registrado en este catálogo?</b><br>
Primero deberá disponer de una cuenta de correo electrónica registrada. Si el usuario es alumno de la UNS, tomará la cuenta de correo registrada en el sistema SIU-Guaraní.<br>
Pasos a seguir:
			<ol>
				<li>Ingresar a la opción “Entrar”  (Arriba a la derecha de la pantalla)</li>
				<li>Activar la cuenta de correo (Esto se realiza por única vez)</li>
				<li>Revisar la cuenta de correo y hacer clik en el link enviado</li>
				<li>Ingresar una contraseña y repetirla</li>
				<li>Ya se encuentra habilidado para la utilización del servicio</li>
			</ol>
		</li>
	</ul>
</p>
